# Generated by Django 4.2.4 on 2023-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  #AUTO increment
                ('intro_title', models.CharField(max_length=50)),
                ('intro_desc', models.TextField()),
            ],
        ),
    ]
